
import { Product } from './types';

export const mockProducts: Product[] = [
  {
    id: 'PROD001',
    tenantId: 'tenant-1',
    name: 'Classic White T-Shirt',
    description: 'A classic crewneck t-shirt in white, made from 100% premium cotton.',
    sku: 'TS-CW-M',
    categoryId: 'tops',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 15,
    price: 25.0,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 5,
    leadTimeDays: 7,
  },
  {
    id: 'PROD002',
    tenantId: 'tenant-1',
    name: 'Wireless Over-Ear Headphones',
    description: 'High-fidelity wireless over-ear headphones with noise-cancellation.',
    sku: 'HD-WOH-BLK',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 35,
    price: 149.99,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 14,
  },
  {
    id: 'PROD003',
    tenantId: 'tenant-1',
    name: 'Artisanal Coffee Beans',
    description: 'A 1kg bag of artisanal whole coffee beans, single-origin from Ethiopia.',
    sku: 'CB-AO-1KG',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 50,
    price: 35.5,
    imageUrl: 'https://images.unsplash.com/photo-1511920183353-3c9c6b738e38?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 10,
    leadTimeDays: 5,
  },
  {
    id: 'PROD004',
    tenantId: 'tenant-1',
    name: 'Minimalist Leather Wallet',
    description: 'A slim, minimalist leather wallet with RFID blocking technology.',
    sku: 'WT-ML-BRN',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 5,
    price: 59.95,
    imageUrl: 'https://images.unsplash.com/photo-1613165341933-d995641702de?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 3,
    leadTimeDays: 10,
  },
  {
    id: 'PROD005',
    tenantId: 'tenant-1',
    name: 'Fitness Tracker Smartwatch',
    description: 'A sleek smartwatch with comprehensive fitness tracking capabilities.',
    sku: 'SW-FT-GRY',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 25,
    price: 199.0,
    imageUrl: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 4,
    leadTimeDays: 12,
  },
  {
    id: 'PROD006',
    tenantId: 'tenant-1',
    name: 'Waterproof Commuter Backpack',
    description: 'A durable, waterproof backpack designed for the daily commute.',
    sku: 'BP-WC-BLK',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 30,
    price: 89.99,
    imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb68c6a62?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 6,
    leadTimeDays: 8,
  },
  {
    id: 'PROD007',
    tenantId: 'tenant-1',
    name: 'Slim Fit Blue Jeans',
    description: 'A pair of classic slim-fit blue denim jeans for everyday wear.',
    sku: 'JN-SF-BLU-32',
    categoryId: 'bottoms',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 40,
    price: 75.0,
    imageUrl: 'https://images.unsplash.com/photo-1602293589922-253499d39c2b?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 7,
    leadTimeDays: 9,
  },
  {
    id: 'PROD008',
    tenantId: 'tenant-1',
    name: 'Insulated Steel Water Bottle',
    description: 'A 32oz stainless steel insulated water bottle, keeps drinks cold for 24 hours.',
    sku: 'WB-IS-32-SIL',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 0,
    price: 29.99,
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-247e961d21a8?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 8,
    leadTimeDays: 6,
  },
  {
    id: 'PROD009',
    tenantId: 'tenant-1',
    name: 'Succulent Plant Set',
    description: 'A set of three beautiful succulent plants in ceramic pots.',
    sku: 'PL-SUC-SET3',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 20,
    price: 24.99,
    imageUrl: 'https://images.unsplash.com/photo-1592235368426-3c5306350284?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 1,
    leadTimeDays: 4,
  },
  {
    id: 'PROD010',
    tenantId: 'tenant-1',
    name: 'RGB Gaming Mouse',
    description: 'A high-performance gaming mouse with customizable RGB lighting.',
    sku: 'MO-GAM-RGB',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 18,
    price: 49.99,
    imageUrl: 'https://images.unsplash.com/photo-1578939655728-399a1733678c?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 15,
  },
  {
    id: 'PROD011',
    tenantId: 'tenant-1',
    name: 'Urban Explorer Jacket',
    description: 'A stylish and functional jacket for urban adventures.',
    sku: 'JKT-UE-GRN-L',
    categoryId: 'tops',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 22,
    price: 120.0,
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d916e6ca4431?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 3,
    leadTimeDays: 10,
  },
  {
    id: 'PROD012',
    tenantId: 'tenant-1',
    name: 'Linen Summer Shorts',
    description: 'Lightweight and breathable linen shorts for summer.',
    sku: 'SHR-LS-BGE-M',
    categoryId: 'bottoms',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 45,
    price: 45.0,
    imageUrl: 'https://images.unsplash.com/photo-1617038220373-f44d962a3d46?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 6,
    leadTimeDays: 8,
  },
  {
    id: 'PROD013',
    tenantId: 'tenant-1',
    name: 'Smart LED Desk Lamp',
    description: 'A modern desk lamp with adjustable brightness and color temperature.',
    sku: 'LP-SLD-WHT',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 12,
    price: 65.0,
    imageUrl: 'https://images.unsplash.com/photo-1594243928198-a7342617f415?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 1,
    leadTimeDays: 12,
  },
  {
    id: 'PROD014',
    tenantId: 'tenant-1',
    name: 'Gourmet Spice Rack',
    description: 'A rotating spice rack with 16 pre-filled gourmet spices.',
    sku: 'KIT-GSR-16',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 30,
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1591866336338-16113b10738a?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 4,
    leadTimeDays: 7,
  },
  {
    id: 'PROD015',
    tenantId: 'tenant-1',
    name: 'Yoga Mat with Carry Strap',
    description: 'A non-slip yoga mat, perfect for all types of yoga.',
    sku: 'FIT-YM-PPL',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 60,
    price: 32.0,
    imageUrl: 'https://images.unsplash.com/photo-1599447462464-a55239a5e848?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 9,
    leadTimeDays: 5,
  },
  {
    id: 'PROD016',
    tenantId: 'tenant-1',
    name: 'Bluetooth Shower Speaker',
    description: 'A waterproof Bluetooth speaker for your shower.',
    sku: 'AUD-BSS-BLU',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 25,
    price: 22.5,
    imageUrl: 'https://images.unsplash.com/photo-1593121925328-3f462a3b9a93?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 2,
    leadTimeDays: 11,
  },
  {
    id: 'PROD017',
    tenantId: 'tenant-1',
    name: 'Hand-poured Soy Candle',
    description: 'A lavender-scented soy candle, hand-poured with love.',
    sku: 'DEC-HSC-LAV',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 80,
    price: 18.0,
    imageUrl: 'https://images.unsplash.com/photo-1614036163992-7c6d649520b9?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP003',
    averageDailySales: 12,
    leadTimeDays: 4,
  },
  {
    id: 'PROD018',
    tenantId: 'tenant-1',
    name: 'Cashmere Winter Scarf',
    description: 'A soft and warm cashmere scarf for cold winters.',
    sku: 'ACC-CWS-GRY',
    categoryId: 'accessories',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 18,
    price: 95.0,
    imageUrl: 'https://images.unsplash.com/photo-1542060748-10c28b62716f?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 2,
    leadTimeDays: 14,
  },
  {
    id: 'PROD019',
    tenantId: 'tenant-1',
    name: 'Portable Espresso Maker',
    description: 'Make espresso on the go with this portable maker.',
    sku: 'KIT-PEM-BLK',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 9,
    price: 55.0,
    imageUrl: 'https://images.unsplash.com/photo-1588194232338-21b369591462?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP002',
    averageDailySales: 1,
    leadTimeDays: 15,
  },
  {
    id: 'PROD020',
    tenantId: 'tenant-1',
    name: 'Organic Cotton Crew Socks (3-Pack)',
    description: 'A 3-pack of comfortable and breathable organic cotton socks.',
    sku: 'ACC-OCS-3PK',
    categoryId: 'essentials',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    stock: 120,
    price: 20.0,
    imageUrl: 'https://images.unsplash.com/photo-1586350343236-d2bf95b1388a?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&w=600',
    supplierId: 'SUP001',
    averageDailySales: 15,
    leadTimeDays: 6,
  },
  ...Array.from({ length: 80 }, (_, i) => {
    const id = 21 + i;
    const categories = ['tops', 'bottoms', 'accessories', 'essentials'];
    const suppliers = ['SUP001', 'SUP002', 'SUP003'];
    return {
      id: `PROD${String(id).padStart(3, '0')}`,
      tenantId: 'tenant-1',
      name: `Generated Product ${id}`,
      description: `Description for generated product ${id}.`,
      sku: `GEN-${id}`,
      categoryId: categories[i % categories.length],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      stock: Math.floor(Math.random() * 100),
      price: parseFloat((Math.random() * 200 + 10).toFixed(2)),
      imageUrl: `https://picsum.photos/seed/PROD${id}/400/400`,
      supplierId: suppliers[i % suppliers.length],
      averageDailySales: Math.floor(Math.random() * 15) + 1,
      leadTimeDays: Math.floor(Math.random() * 12) + 3,
    };
  })
];
