import { Transaction } from './types';

export const mockTransactions: Transaction[] = [
    {
        id: 'TRN001',
        tenantId: 'tenant-1',
        productId: 'PROD001',
        locationId: 'LOC001',
        type: 'Sale',
        quantity: 2,
        transactionDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
        updatedAt: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    },
    {
        id: 'TRN002',
        tenantId: 'tenant-1',
        productId: 'PROD002',
        locationId: 'LOC001',
        type: 'Purchase',
        quantity: 10,
        transactionDate: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
        updatedAt: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    },
    {
        id: 'TRN003',
        tenantId: 'tenant-1',
        productId: 'PROD003',
        locationId: 'LOC001',
        type: 'Sale',
        quantity: 5,
        transactionDate: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
        updatedAt: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    },
    {
        id: 'TRN004',
        tenantId: 'tenant-1',
        productId: 'PROD001',
        locationId: 'LOC001',
        type: 'Sale',
        quantity: 1,
        transactionDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
        updatedAt: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    },
     {
        id: 'TRN005',
        tenantId: 'tenant-1',
        productId: 'PROD007',
        locationId: 'LOC001',
        type: 'Purchase',
        quantity: 20,
        transactionDate: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
        createdAt: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
        updatedAt: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    },
];
